### ISSUE TITLE
Service calls

### ISSUE THREAD

**Issue by lenardpalko** [khepin/KhepinYamlFixturesBundle#56]
Break from issue #23 : 

viliam-husar : allow service calls before and after fixtures file is loaded (not after object is persisted)
khepin : service calls: can't remember very precisely how it worked, have to look at it again

**Comment by lenardpalko** [comment]
Currently from what I see in the code viliam-husar is right : the services are called just at object level, not before/after fixture files are loaded, but they are run right after the object is created and  not after persist is called on entity manager.

So @khepin the question is does the bundle want to support service calls before/after fixture file load ?
I could work on this if it's a scope ...

Thanks

**Comment by khepin** [comment]
Well if you have an immediate use for it, I'd say go ahead. Otherwise, This bundle has been roughly stable for a long time and I'm not sure there's much interest in this.

**Comment by lenardpalko** [comment]
Currently I don't have a use case for this either, so maybe we can close this issue also until someone else has this use case.
