### ISSUE TITLE
Normalize tests

### ISSUE THREAD

**Issue by lenardpalko** [khepin/KhepinYamlFixturesBundle#57]
Break from issue #23 : 

viliam-husar : normalize tests
khepin : Tests: sure, I love tests!

**Comment by lenardpalko** [comment]
@viliam-husar @khepin : what do you mean by normalize tests ?

**Comment by khepin** [comment]
Can't remember. I think tests are in good shape on this bundle right now though.

**Comment by lenardpalko** [comment]
I also think tests are pretty ok.

So we can close this issue.
