### ISSUE TITLE
Warning: Illegal string offset 'model' in v.1.0.0 when loading fixtures

### ISSUE THREAD

**Issue by dmitry-pro** [khepin/KhepinYamlFixturesBundle#62]
Hi! I just tried to use this bundle in my project, and found this error:

`$ console khepin:yamlfixtures:load`

 `[Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Illegal string offset 'model'`            

`Exception trace:
 () at /var/www/my_app/vendor/khepin/yaml-fixtures-bundle/Khepin/YamlFixturesBundle/Loader/YamlLoader.php:112
 Symfony\Component\Debug\ErrorHandler->handleError() at /var/www/my_app/vendor/khepin/yaml-fixtures-bundle/Khepin/YamlFixturesBundle/Loader/YamlLoader.php:112
 Khepin\YamlFixturesBundle\Loader\YamlLoader->loadFixtures() at /var/www/my_app/vendor/khepin/yaml-fixtures-bundle/Khepin/YamlFixturesBundle/Command/FixturesLoadCommand.php:66
...`

I have investigated what's the problem, and found a weird place in vendor/khepin/yaml-fixtures-bundle/Khepin/YamlFixturesBundle/Loader/YamlLoader.php:107

`$fixture_data = Yaml::parse($file);`

After I changed it to

`$fixture_data = Yaml::parse(file_get_contents($file));`

it worked as expected.

Is this some kind of mistake, or is it just caused by different versions of Yaml component - anyways it's more clear to pass the file data than file name. Could You fix it please? I have found it in both 1.0.0 and 0.8.1 versions, so my pull request is not the best way to do it for all versions.

Thank You!

**Comment by khepin** [comment]
Hi, you mention a pull-request in your comment but I don't see any. If you have something to submit, that would be the easiest.
I'd be happy to review what you have and see if something needs to be merged.

**Comment by stphane** [comment]
Hello ! I'm having the exact same problem. Fix seems so straight forward but there hasn't be any one released yet, isn't it ? Thank You!

**Comment by khepin** [comment]
Hey @stphane do you by chance have a fix?
I'd be happy to merge a pull request fixing the issue if you could make one.

Do you think that's possible?

**Comment by stphane** [comment]
@khepin Actualy, dimitry-pro gave the fix already, I expected a new revision to come to life with the following changes in _khepin/yaml-fixtures-bundle/Khepin/YamlFixturesBundle/Loader/YamlLoader.php_ on line 107 (v1.0.0):  
`$fixture_data = Yaml::parse($file);`
been replaced by  
`$fixture_data = Yaml::parse(file_get_contents($file));`

**Comment by khepin** [comment]
Alright, since it's all there then, would you mind making an actual pull request for it? That'll help immensely.

Thanks

**Comment by stphane** [comment]
Code is okey on [master branch](https://github.com/khepin/KhepinYamlFixturesBundle/commit/912a61f1d4a99bdfe04d838dc36c44621a4b3772#diff-0).

**Comment by khepin** [comment]
Oh! Gotcha. I never realized the code was already fixed and the only thing needed was a version push.
I'll work on that now.

**Comment by khepin** [comment]
Alright, I've spent the afternoon trying to make those tests pass on Travis and all I get is a composer memory error.
Can't figure it out, any help on this one is welcome.

**Comment by stphane** [comment]
Great ! Concerning the memory error, does your php cli has xdebug enabled ?
I had memory issues at some point and disabling the extension did help !

**Comment by khepin** [comment]
try it and let me know
