### ISSUE TITLE
Passing contructor arguments does not work for Mongo

### ISSUE THREAD

**Issue by mposchl** [khepin/KhepinYamlFixturesBundle#64]
```
//MongoYamlFixture.php
...
$mapping = array_keys($metadata->fieldMappings);
// Instantiate new object
$object = new $class;
...
```

**Comment by khepin** [comment]
I'm really not sure what this is referring to. If you're having issues with using this library, please detail a bit more what the issues are.

**Comment by mposchl** [comment]
You mention in the documentation in the section Constructor, that you may pass arguments to the entity's constructor, but the code, that does this, is implemented only for ORM fixtures (with no mention, that this works only for ORM, not for mongo etc.). My comment shows the code snippet from mongo fixture, where you can see, that there's no passing arguments to the constructor via reflection, as in orm fixture implementation.

**Comment by khepin** [comment]
Should work with last release now.

**Comment by mposchl** [comment]
great Sebastian, thank you!
